=== baltth/cdb-check/config.schema.json
{
  "type": "object",
  "properties": {
    "base_dirs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "libraries": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "compile_units": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "flags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "flags_by_compiler": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "default": {}
    },
    "flags_by_library": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "default": {}
    },
    "flags_by_file": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "default": {}
    },
    "consistency": {
      "type": "integer",
      "enum": [
        0,
        1,
        2
      ],
      "default": 0
    },
    "verbose": {
      "type": "boolean",
      "default": false
    },
    "summary": {
      "type": "boolean",
      "default": false
    }
  },
  "description": "JSON schema for cdb-check configuration",
  "$schema": "http://json-schema.org/draft-06/schema#"
}

=== baltth/cdb-check/test_data/cfg_complex.json
{
  "$schema": "../config.schema.json",
  "base_dirs": ["/path/to/project/prj", "/path/to/toolchains"],
  "flags": ["Wall", "Wextra", "g", "I[...]/include"],
  "flags_by_compiler": {
    "**/aarch64-oe-linux-*": ["finline-limit=64", "D__ARM_PCS_VFP"]
  },
  "flags_by_library": {
    "lib": ["DLIB_DEFINE=1", "pedantic"]
  },
  "flags_by_file": {
    "**/*.c": ["std=c11"],
    "**/*.cpp": ["std=c++11", "pedantic"]
  }
}
